// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('apiKey', defaultValue: ''),
    appId: '1:793463336809:web:d681af225315177f8257f8',
    messagingSenderId: '793463336809',
    projectId: 'othli-497404',
    authDomain: 'othli-497404.firebaseapp.com',
    storageBucket: 'othli-497404.firebasestorage.app',
    measurementId: 'G-JMM9SJ9X5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('apiKey_android', defaultValue: ''),
    appId: '1:793463336809:android:8d42a5cb73042ec78257f8',
    messagingSenderId: '793463336809',
    projectId: 'othli-497404',
    storageBucket: 'othli-497404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('apiKey_ios', defaultValue: ''),
    appId: '1:793463336809:ios:5ba20dcee4e7b03b8257f8',
    messagingSenderId: '793463336809',
    projectId: 'othli-497404',
    storageBucket: 'othli-497404.firebasestorage.app',
    iosClientId: '793463336809-qshohm989u12mhic5n3brconjt437aj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.othliFront',
  );
}
